### PR TITLE
Update site footer and add link to Support page on Bazel site.

### PR DESCRIPTION
**Pull request by davidzchen**
Issue: bazelbuild/bazel#19

### CODE REVIEW

**Comment by davidzchen** [comment]
screen shot 2017-06-22 at 1 27 26 am

**Comment by steren** [comment]
Sorry, I sent a PR already: https://github.com/bazelbuild/bazel-blog/pull/12 can you take a look at it instead? It brings the new CSS structure tool

**Comment by steren** [comment]
Also, please complete https://github.com/bazelbuild/bazel-website/pull/29 before syncing the changes on the other sites

**Comment by davidzchen** [comment]
Ah no worries. Thanks!

**Pull request closed without merging**
