### PR TITLE
Blog post to introduce the dynamic spawn scheduler

### PR DESCRIPTION
**Pull request by jmmv**

### CODE REVIEW

**Comment by jmmv** [comment]
I see a lot of people were auto-added to this PR as code owners. I'm assuming only the four of you can approve and merge this?

FYI @spomorski and @jin already reviewed this draft in https://docs.google.com/document/d/1IOsjFGtrbE-3Wk01b7EO0CyD4dVdjyCt9BaW-4vdf2s/edit and this is pretty-much a copy/paste with a tiny couple of tweaks.

**Comment by spomorski** [comment]
I can merge if nobody else has objections.

**Comment by jmmv** [comment]
Given that this CODEOWNERS thing is pretty new and that your approval seems sufficient, I don't think we need to wait for anyone else and we can do as usual. It's just that the icons that GitHub added for the owners confused me initially and I wasn't sure if anybody else could lgtm.

**Comment by jmmv** [comment]
Spoke to aiuto@ and I was indeed confused by the strange UI. Merging!

**Pull request merged**
