### PR TITLE
Blog post for bazel 0.22.0

### PR DESCRIPTION
**Pull request by aehlig**

### CODE REVIEW

**Comment by laurentlb** [comment]
There was comments on the blog post draft. Why were they not resolved first?

**Comment by philwo** [comment]
@laurentlb Good question. For my side, I'm just a reviewer on the PR and didn't know what to look for (except for obvious errors in the Markdown code), so I just LGTM'd it after making sure that the "Preview" in GitHub looks fine.

@aehlig ?

**Comment by laurentlb** [comment]
and it seems like (some) changes that were made in the doc are lost?

**Comment by laurentlb** [comment]
Ping @aehlig

**Pull request merged**
