### PR TITLE
Blog post about backward compatibility

### PR DESCRIPTION
**Pull request by laurentlb**
To be published tomorrow.

### CODE REVIEW

**Comment by steren** [comment]
Ping @davidzchen to make sure the blog is re-published, I do not think things are automated yet.

**Comment by laurentlb** [comment]
Who can review/approve this?

**Comment by steren** [comment]
I assigned @damienmg as a reviewer, please pick a team member as reviewer for your next blog post.

**Comment by michelleirvine** [comment]
I've made some edits and have some questions - see the updated .md file

**Comment by michelleirvine** [comment]
Above I suggested changing a line to "If your tests with the new change are successful, you can update to the new version", but "tests" is a bad word to use in this context as well because I don't mean "bazel test". 

Maybe something like:

"After verifying your project with the released changes, you can update to the new version."

**Comment by laurentlb** [comment]
LGTM!

Yes, we can use "flag".
Yes, we should announce when a flag is removed.
Yes, as long as the flag is present, user can decide to enable or disable it.
It's primarily for Skylark, but it may be used for the rest of Bazel.

I'm going on vacation, feel free to push with your changes.
Thanks a lot!

**Comment by michelleirvine** [comment]
Okay thanks, Laurant I'll make these last changes on Monday.

Have a good vacation!

**Comment by michelleirvine** [comment]
@damienmg 
Damien,

Before we publish this blog post, I'd like to confirm the following with the larger Bazel team:
1) Can you confirm if the larger Bazel team is introducing incompatible changes (so elsewhere in the code, not just in the extensions/skylark area)? If so, we will need a topic about backward compatibility outside of the extensions section (currently: https://docs.bazel.build/versions/master/skylark/backward-compatibility.html).
2) Is everyone okay with the process to introduce incompatible changes behind flags (need to confirm especially if other teams are introducing incompatible changes)? If we're announcing this we need to do it consistently.
3) Is everyone okay with the process to announce the progression of incompatible changes in the release notes? If so, I'll add info about this to the contribute page (I'm working on a section about doc contributions).
4) Blog post states that once we hit 1.0, major versions will be ~once a year. This okay to state?

**Comment by dslomov** [comment]
My  take:
1. Yes we encourage people to use flags for incompatible changes. Let's not block this blog post on reshuffling other documentation. Feel free to update it later after documentation is updated.
2. Yes, but not all incompatible changes need to have a flag (it is up to individual teams on case-by-case basis)
3. Yes - they MUST be announced in release notes
4. Yes.

**Comment by damienmg** [comment]
Dmitry was faster than I, seconding what Dmitry said.

**Comment by michelleirvine** [comment]
Thanks Dmitry and Damien - if not all incompatible changes need a flag, we need a bit of rewording. PTAL, after these change I'm okay with publishing.

Changes:
- reworded a line to: "For most breaking changes, we will add a flag"
- added:  "Verify your project again with the new version, as some small incompatible changes are not introduced behind flags."

**Comment by michelleirvine** [comment]
@damienmg and @dslomov can you look at the two changes above and let me know if this is good to publish?

**Comment by laurentlb** [comment]
LGTM

**Comment by laurentlb** [comment]
It's still not on https://blog.bazel.build/?

**Comment by steren** [comment]
ping @davidzchen for a deployment.

**Pull request merged**
