### PR TITLE
Fix internal link in build performance blog

### PR DESCRIPTION
**Pull request by zhengwei143**

### CODE REVIEW

**Review by meisterT — APPROVED** [review]
Probably you want to squash the commits

**Review by jin — APPROVED** [review]

**Comment by zhengwei143** [comment]
Commits fixed, didn't rebase previously.

**Comment by jin** [comment]
Github supports "squash and merge", so no need to do that manually :)

**Comment by zhengwei143** [comment]
TIL - I barely use github :)

**Pull request merged**
