### PR TITLE
Add Bazel community roundup for 2022 June and July.

### PR DESCRIPTION
**Pull request by jin**

### CODE REVIEW

**Review by sventiffe — APPROVED** [review]

**Review by jdob — APPROVED** [review]
LGTM

**Review by hicksjoseph — APPROVED** [review]
LGTM

**Comment by jin** [comment]
I no longer have merge permissions for this repo. Can someone help to merge this please?

**Comment by sventiffe** [comment]
Can you try again, I've added you to the repo granting write access. @jdob is this ok? I think regular contributors should be enabled to merge approved changes without admins being the bottleneck. Or would you prefer to route all writes through admins as long as the blog is being revamped?

**Comment by jin** [comment]
Thanks @sventiffe!

**Pull request merged**
