### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by meteorcloudy**
https://github.com/bazelbuild/bazel-blog/pull/286#issuecomment-1335424639

### CODE REVIEW

**Review by aiuto — COMMENTED** [review]
Should @jin be here?   He's really changed jobs dramatically since he was added.
I also wonder if I should be here or @sventiffe ?

**Comment by jin** [comment]
My main job has changed but I'm still happy to help push things through once in a while, especially for the rare urgent approvals (https://github.com/bazelbuild/bazel-blog/pull/282, https://github.com/bazelbuild/bazel-blog/pull/284). I'm fine with it either way regardless.

**Review by meisterT — APPROVED** [review]
This is good as it increases timezone coverage.

**Review by jin — APPROVED** [review]

**Comment by meteorcloudy** [comment]
> I also wonder if I should be here or @sventiffe ?

I'm merging this one first, if you think other people should also be here, feel free to send a PR ;)

**Pull request merged**
