### PR TITLE
docs: document manual process to update the blog

### PR DESCRIPTION
**Pull request by laszlocsomor**

### CODE REVIEW

**Comment by damienmg** [comment]
So I was a bit hesitant to document this this way and wanted to play a bit with with Google cloud container builder so I set up a system that does the push :) send you a PR

**Comment by laszlocsomor** [comment]
> So I was a bit hesitant to document this this way 

Can you explain why? I believe understanding the manual process is important, perhaps more than having an automated process. The manual process is a fallback mechanism, and knowing it helps diagnosing problems with the automated process.

**Comment by damienmg** [comment]
This manual process indicate to use a CI machine (which we should not modify the state...). So many manual steps is error-prone.

The PR still has the manual step but wrapped in a one liner script.

**Comment by laszlocsomor** [comment]
This is probably obsolete.

**Pull request closed without merging**
