### PR TITLE
post about bazel in homebrew

### PR DESCRIPTION
**Pull request by buchgr**

### CODE REVIEW

**Comment by edbaunton** [comment]
I actually had the following experience when trying to convert my existing homebrew bazel installation over to the tap; did I miss something or could the docs be refined more?

I basically had to totally uninstall bazel and reinstall.

```
ed $ brew tap bazelbuild/tap
...
ed $ brew tap-pin bazelbuild/tap
==> Pinned bazelbuild/tap
ed $ brew install bazel
Warning: bazel is provided by core, but is now shadowed by bazelbuild/tap/bazel.
To refer to the core formula, use Homebrew/core/bazel instead.
==> Installing bazel from bazelbuild/tap
Error: bazel 0.15.2 is already installed
To upgrade to 0.16.1, run `brew upgrade bazel`
ed $ brew upgrade bazel
Error: bazel 0.15.2 already installed
ed $ brew uninstall bazel
Uninstalling /usr/local/Cellar/bazel/0.15.2... (12 files, 109MB)
ed $ brew install bazel
Warning: bazel is provided by core, but is now shadowed by bazelbuild/tap/bazel.
To refer to the core formula, use Homebrew/core/bazel instead.
==> Installing bazel from bazelbuild/tap
```

**Comment by buchgr** [comment]
Hi Ed,

thanks for the feedback. Yes you need to uninstall Bazel from homebrew core when using our tap. I mention this in the blog post

> Please note that if you have installed Bazel from the homebrew core formula in
> the past you will have to uninstall it first by running `brew uninstall bazel`.

Do you think this should be in a more prominent place?

**Comment by edbaunton** [comment]
Oh my mistake, I simply stopped reading after running those commands and started having trouble :) The current content is fine in that case (but maybe moving that note up would benefit other lazy readers like me).

**Comment by buchgr** [comment]
thanks @edbaunton. I moved the note up a bit.

**Pull request merged**
