### PR TITLE
xml_escape blog post title

### LINKED ISSUE #275: RSS feed returns invalid xml
Hi, just wanted to add the bazel blog to my blog accumulator, 

The problem is, the java script rss parser I use can not handle the returned xml from https://blog.bazel.build/feed.xml
```
error: Error: Invalid character in entity name
Line: 9
Column: 32
```

also, a browser has problems displaying the content of the rss feed
Screenshot 2022-07-23 at 19 28 11

It would be awesome if this could be fixed, so I do not miss any blogs in future, and the bazel blog can be part of [the SwedenCpp C++ blog feed](http://www.swedencpp.se/blogs).
Thank you!

### PR DESCRIPTION
**Pull request by a4z**
Also blog title should escape special characters  
Fixes #275

### CODE REVIEW

**Review by fweikert — APPROVED** [review]

**Comment by a4z** [comment]
Thank you for your approval, @fweikert !

There is still the message that 1 review is required. 
Is it possible to request a review from someone with write access, or will this happen automatically?

**Comment by fweikert** [comment]
I hope that @aiuto 's review should be enough.

**Review by aiuto — APPROVED** [review]
Looks OK. But I have no idea what it doesk.

**Comment by a4z** [comment]
> Looks OK. But I have no idea what it doesk.

Removing - for content - illegal html characters and replacing them with the html escape sequences, like 
* `&` escape to `&amp;`
* `<` escape to `&lt;`
* `>` escape to `&gt;`  

there might be, and are for sure, more.  

Without that, it's not possible to have a title / content like `Look at my cool C++ template<typename T> magic` .

For json feeds, same rules apply.

The blog content was excepted already correctly, with this PR, also the title will be escaped, and a title like [Announcing Bazel & JetBrains co-maintenance of IntelliJ IDEA Bazel Plugin](https://blog.bazel.build/2022/07/11/Bazel-IntelliJ-Update.html) will  not cause problems since the `&` will be replaced. 

What I do not understand is, why did this ever work for the bazel blog without that .... 🤔 ... 😄

**Comment by fweikert** [comment]
Tony, can you please merge this PR? I don't have the permissions to do so.

**Comment by aiuto** [comment]
Oh.  Sure.  I did not know that.

**Pull request merged**
